### ISSUE TITLE
DSCResources do not match when they should

### ISSUE THREAD

**Issue by jowj** [mrled/lability-tutorial#1]
ConfigurationData.SIMPLE.psd1:
```
            DSCResource = @(
                @{ Name = 'xComputerManagement'; RequiredVersion = '1.9.0.0'; }
                @{ Name = 'xNetworking'; RequiredVersion = '3.2.0.0'; }
            );
```

Configure.SIMPLE.ps1
```
    Import-DscResource -Module xComputerManagement -ModuleVersion 4.1.0.0
    Import-DscResource -Module xNetworking -ModuleVersion 5.7.0.0
```
When these module versions don't match the deploy script will not run.

This issue can be seen here, in chapter 2:
http://me.micahrl.com/lability-tutorial/02-Simple/

**Comment by jowj** [comment]
This issue also occurs within Chapter 5's "SIMPLENET" example. Interestingly enough, the VMs build in that chapter, but IP addresses do not get set since the modules do not match.

**Comment by mrled** [comment]
Fixed. Thanks!
