### ISSUE TITLE
Chapter 5 missing documentation link

### ISSUE THREAD

**Issue by jowj** [mrled/lability-tutorial#3]
Issue exists [here](http://me.micahrl.com/lability-tutorial/05-SimpleNetwork/#lab-exercises-and-files), in the exercises portion of the chapter. Chapter advises that you try and remote between the two guests, but this won't work without adjusting a guest's trustedhost store. 

Add links to documentation: http://me.micahrl.com/lability-tutorial/backmatter/concepts/powershell/remoting

**Comment by mrled** [comment]
Thanks! 

Note to self 1: call out the trusted hosts thing specifically in the exercise text, since the PS remoting article is long

Note to self 2: the VMs in that chapter will need to have the category for their network set to private, not public... make sure this is noted in the chapter too
